# Generated by Django 6.0.6 on 2026-06-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talles',
            field=models.ManyToManyField(blank=True, related_name='productos', to='tienda.talle', verbose_name='Talles Disponibles'),
        ),
    ]
