# Generated by Django 6.0.6 on 2026-06-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_talles'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Disponible para la venta'),
        ),
        migrations.AddField(
            model_name='talle',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Disponible para la venta'),
        ),
    ]
